// Auto-generated by `npm run db:generate` (drizzle-kit). Do not edit by hand.
import journal from './meta/_journal.json';
import m0000 from './0000_initial.sql';
import m0001 from './0001_skill_position.sql';
import m0002 from './0002_unique_routine_completion.sql';

export default {
  journal,
  migrations: {
    m0000,
    m0001,
    m0002,
  },
};
