import React, { useCallback, useState } from 'react';
import { View, Text, Pressable } from 'react-native';
import DraggableFlatList, { RenderItemParams, ScaleDecorator } from 'react-native-draggable-flatlist';
import { useFocusEffect, useRouter } from 'expo-router';
import { Settings as SettingsIcon, Plus, Archive, Trash2 } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from '@/hooks/useTheme';
import { useRoutineStore, selectDailyProgress } from '@/stores/routineStore';
import { useSettingsStore } from '@/stores/settingsStore';
import { useGreeting } from '@/hooks/useGreeting';
import { ProgressRing } from '@/components/ProgressRing';
import { RoutineItem } from '@/components/RoutineItem';
import { EmptyState } from '@/components/EmptyState';
import { AddItemSheet } from '@/components/AddItemSheet';
import { refreshRoutineWidget } from '@/widgets/refreshWidget';
import type { RoutineDisplayItem } from '@/types';

export default function RoutineScreen() {
 const theme = useTheme(); const router = useRouter(); const { items, isLoading, load, toggleItem, reorderActiveItems, archiveHabit, deleteHabit, archiveSkill, deleteSkill, archiveTodo, deleteTodo } = useRoutineStore(); const reduceMotion = useSettingsStore((s) => s.reduceMotion); const greeting = useGreeting(); const [creating, setCreating] = useState(false); const [selectedId, setSelectedId] = useState<string | null>(null);
 useFocusEffect(useCallback(() => { load(); }, [load]));
 const progress = selectDailyProgress(items); const activeItems = items.filter((i) => !i.completed); const completedItems = items.filter((i) => i.completed);
 const handleItemCreated = async (category: 'habit' | 'skill' | 'todo') => { await load(); refreshRoutineWidget(); };
 const archive = async (item: RoutineDisplayItem) => { if (item.type === 'habit') await archiveHabit(item.sourceId); else if (item.type === 'skill') await archiveSkill(item.sourceId); else await archiveTodo(item.sourceId); setSelectedId(null); };
 const remove = async (item: RoutineDisplayItem) => { if (item.type === 'habit') await deleteHabit(item.sourceId); else if (item.type === 'skill') await deleteSkill(item.sourceId); else await deleteTodo(item.sourceId); setSelectedId(null); };
 const renderItem = ({ item }: RenderItemParams<RoutineDisplayItem>) => <ScaleDecorator><View><Pressable onLongPress={() => setSelectedId(selectedId === item.id ? null : item.id)} delayLongPress={300}><RoutineItem item={item} onToggle={() => toggleItem(item)} reduceMotion={reduceMotion} /></Pressable>{selectedId === item.id && <View style={{ flexDirection: 'row', gap: theme.spacing[3], paddingHorizontal: theme.spacing[4], paddingBottom: theme.spacing[3] }}><Pressable onPress={() => archive(item)} style={{ flex: 1, minHeight: theme.semantic.touchMinimum, borderRadius: theme.radius.sm, backgroundColor: theme.colors.background.surface, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }}><Archive size={18} color={theme.colors.text.secondary} /><Text style={{ color: theme.colors.text.primary }}>Archive</Text></Pressable><Pressable onPress={() => remove(item)} style={{ flex: 1, minHeight: theme.semantic.touchMinimum, borderRadius: theme.radius.sm, backgroundColor: theme.colors.background.surface, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }}><Trash2 size={18} color={theme.colors.semantic.error} /><Text style={{ color: theme.colors.semantic.error }}>Delete</Text></Pressable></View>}</View></ScaleDecorator>;
 return <SafeAreaView style={{ flex: 1, backgroundColor: theme.colors.background.primary }} edges={['top']}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: theme.spacing[4], paddingTop: theme.spacing[2] }}><Text style={{ color: theme.colors.text.primary, fontSize: theme.typography.title.fontSize, fontFamily: theme.typography.title.fontFamily }}>{greeting}</Text><View style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing[4] }}><Pressable onPress={() => router.push('/archive/habits')}><Archive color={theme.colors.text.secondary} size={theme.iconSize.lg} /></Pressable><Pressable onPress={() => router.push('/modal')}><SettingsIcon color={theme.colors.text.secondary} size={theme.iconSize.lg} /></Pressable></View></View><View style={{ alignItems: 'center', paddingVertical: theme.spacing[6] }}><ProgressRing completed={progress.completed} total={progress.total} reduceMotion={reduceMotion} /></View>
 {items.length === 0 && !isLoading ? <EmptyState icon="Sunrise" title="Nothing here yet" description="Add a habit, skill, or to-do to build today's routine." actionLabel="Add an item" onAction={() => setCreating(true)} /> : <View style={{ flex: 1 }}><DraggableFlatList data={activeItems} keyExtractor={(item) => item.id} onDragEnd={({ data }) => reorderActiveItems(data)} activationDistance={20} renderItem={renderItem} contentContainerStyle={{ paddingBottom: completedItems.length ? 0 : theme.spacing[16] }} />{completedItems.length > 0 && <><View style={{ height: 1, backgroundColor: theme.colors.border.default, marginVertical: theme.spacing[3], marginHorizontal: theme.spacing[4] }} />{completedItems.map((item) => <View key={item.id}><Pressable onLongPress={() => setSelectedId(selectedId === item.id ? null : item.id)} delayLongPress={300}><RoutineItem item={item} onToggle={() => toggleItem(item)} reduceMotion={reduceMotion} /></Pressable>{selectedId === item.id && <View style={{ flexDirection: 'row', gap: theme.spacing[3], paddingHorizontal: theme.spacing[4], paddingBottom: theme.spacing[3] }}><Pressable onPress={() => archive(item)} style={{ flex: 1, minHeight: theme.semantic.touchMinimum, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }}><Archive size={18} color={theme.colors.text.secondary} /><Text style={{ color: theme.colors.text.primary }}>Archive</Text></Pressable><Pressable onPress={() => remove(item)} style={{ flex: 1, minHeight: theme.semantic.touchMinimum, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }}><Trash2 size={18} color={theme.colors.semantic.error} /><Text style={{ color: theme.colors.semantic.error }}>Delete</Text></Pressable></View>}</View>)}</>}</View>}
 <Pressable onPress={() => setCreating(true)} style={{ position: 'absolute', right: theme.spacing[4], bottom: theme.spacing[6], width: 56, height: 56, borderRadius: theme.radius.full, backgroundColor: theme.colors.accent.primary, alignItems: 'center', justifyContent: 'center' }}><Plus color={theme.colors.text.primary} size={24} /></Pressable><AddItemSheet visible={creating} onClose={() => setCreating(false)} onCreated={handleItemCreated} /></SafeAreaView>;
}
