import React, { useCallback, useState } from 'react';
import { View, Text, SectionList, Pressable } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import DraggableFlatList, { RenderItemParams, ScaleDecorator } from 'react-native-draggable-flatlist';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as Icons from 'lucide-react-native';
import { useTheme } from '@/hooks/useTheme';
import { useSkillsStore } from '@/stores/skillsStore';
import { skillsService } from '@/services/skillsService';
import { EmptyState } from '@/components/EmptyState';
import { BottomSheet } from '@/components/BottomSheet';
import { InputField } from '@/components/InputField';
import { Button } from '@/components/Button';
import type { Skill } from '@/database/schema';

export default function SkillsScreen() {
 const theme = useTheme(); const router = useRouter();
 const { active, inactive, completed, completedToday, load, create, activate, complete, archive, delete: deleteSkill, reorder } = useSkillsStore();
 const [creating, setCreating] = useState(false); const [title, setTitle] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null); const [practiceMinutes, setPracticeMinutes] = useState<Record<string, number>>({}); const [practiceSkill, setPracticeSkill] = useState<Skill | null>(null); const [hours, setHours] = useState(''); const [practiceError, setPracticeError] = useState<string | null>(null);
 const refresh = useCallback(async () => { await load(); const all = [...active, ...inactive, ...completed]; const totals: Record<string, number> = {}; await Promise.all(all.map(async (s) => { const sessions = await skillsService.getSessionHistory(s.id); totals[s.id] = sessions.reduce((sum, session) => sum + session.durationMinutes, 0); })); setPracticeMinutes(totals); }, [load]);
 useFocusEffect(useCallback(() => { refresh(); }, [refresh]));
 const sections = [{ title: 'Inactive', data: inactive }, { title: 'Completed', data: completed }].filter((s) => s.data.length > 0);
 const handleCreate = async () => { if (!title.trim()) return; setSaving(true); setError(null); try { await create(title); setTitle(''); setCreating(false); } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong.'); } finally { setSaving(false); } };
 const openPractice = (skill: Skill) => { if (completedToday.has(skill.id)) return; setPracticeSkill(skill); setHours(''); setPracticeError(null); };
 const savePractice = async () => { const value = Number(hours); if (!Number.isFinite(value) || value <= 0) { setPracticeError('Enter the hours you practiced today.'); return; } try { await complete(practiceSkill!.id, Math.round(value * 60)); setPracticeSkill(null); } catch (e) { setPracticeError(e instanceof Error ? e.message : 'Could not save practice.'); } };
 const actionRow = (skill: Skill) => selectedId === skill.id ? <View style={{ flexDirection: 'row', gap: theme.spacing[3], paddingHorizontal: theme.spacing[4], paddingBottom: theme.spacing[3] }}><Pressable onPress={() => { archive(skill.id); setSelectedId(null); }} style={{ flex: 1, minHeight: theme.semantic.touchMinimum, borderRadius: theme.radius.sm, backgroundColor: theme.colors.background.surface, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }}><Icons.Archive size={18} color={theme.colors.text.secondary} /><Text style={{ color: theme.colors.text.primary }}>Archive</Text></Pressable><Pressable onPress={() => { deleteSkill(skill.id); setSelectedId(null); }} style={{ flex: 1, minHeight: theme.semantic.touchMinimum, borderRadius: theme.radius.sm, backgroundColor: theme.colors.background.surface, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }}><Icons.Trash2 size={18} color={theme.colors.semantic.error} /><Text style={{ color: theme.colors.semantic.error }}>Delete</Text></Pressable></View> : null;
 const renderSkill = (item: Skill, section: string) => { const IconComponent = (Icons as Record<string, any>)[item.icon ?? 'Sparkles'] ?? Icons.Sparkles; const totalHours = ((practiceMinutes[item.id] ?? 0) / 60).toFixed(1); return <><Pressable onLongPress={() => setSelectedId(selectedId === item.id ? null : item.id)} delayLongPress={300}><View style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: theme.spacing[3], paddingHorizontal: theme.spacing[4], gap: theme.spacing[3] }}><View style={{ width: theme.iconSize.xl, height: theme.iconSize.xl, borderRadius: theme.radius.sm, backgroundColor: theme.colors.background.card, alignItems: 'center', justifyContent: 'center' }}><IconComponent size={theme.iconSize.md} color={theme.colors.text.secondary} /></View><View style={{ flex: 1 }}><Text style={{ color: theme.colors.text.primary, fontSize: theme.typography.body.fontSize }}>{item.title}</Text><Text style={{ color: theme.colors.text.secondary, fontSize: theme.typography.caption.fontSize }}>{totalHours} h practiced</Text></View>{section === 'Inactive' && <Button label="Activate" variant="secondary" onPress={() => activate(item.id)} />}{section === 'Active' && <Button label={completedToday.has(item.id) ? 'Done today' : 'Complete'} variant="secondary" disabled={completedToday.has(item.id)} onPress={() => openPractice(item)} />}</View></Pressable>{actionRow(item)}</>; };
 return <SafeAreaView style={{ flex: 1, backgroundColor: theme.colors.background.primary }} edges={['top']}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: theme.spacing[4] }}><Text style={{ color: theme.colors.text.primary, fontSize: theme.typography.title.fontSize, fontFamily: theme.typography.title.fontFamily }}>Skills</Text><View style={{ flexDirection: 'row', gap: theme.spacing[4] }}><Pressable onPress={() => router.push('/archive/skills')}><Icons.Archive color={theme.colors.text.secondary} size={theme.iconSize.lg} /></Pressable><Pressable onPress={() => setCreating(true)}><Icons.Plus color={theme.colors.accent.primary} size={theme.iconSize.lg} /></Pressable></View></View>
 {active.length === 0 && sections.length === 0 ? <EmptyState icon="Sparkles" title="No skills yet" description="Create a skill to start deliberate, long-term practice." actionLabel="Create a skill" onAction={() => setCreating(true)} /> : <View style={{ flex: 1 }}>{active.length > 0 && <><Text style={{ color: theme.colors.text.secondary, fontSize: theme.typography.label.fontSize, paddingHorizontal: theme.spacing[4], paddingBottom: theme.spacing[2] }}>ACTIVE</Text><SectionList sections={[{ title: '', data: active }]} keyExtractor={(item) => item.id} renderItem={({ item }) => renderSkill(item, 'Active')} renderSectionHeader={() => null} contentContainerStyle={{ paddingBottom: theme.spacing[2] }} /></>}{sections.length > 0 && <SectionList sections={sections} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingBottom: theme.spacing[16] }} renderSectionHeader={({ section }) => <Text style={{ color: theme.colors.text.secondary, fontSize: theme.typography.label.fontSize, paddingHorizontal: theme.spacing[4], paddingTop: theme.spacing[4], paddingBottom: theme.spacing[2] }}>{section.title.toUpperCase()}</Text>} renderItem={({ item, section }) => renderSkill(item, section.title)} />}</View>}
 <BottomSheet visible={creating} onClose={() => { setCreating(false); setError(null); }}><View style={{ gap: theme.spacing[4] }}><Text style={{ color: theme.colors.text.primary, fontSize: theme.typography.card.fontSize, fontFamily: theme.typography.card.fontFamily }}>New Skill</Text><InputField label="Title" value={title} onChangeText={setTitle} placeholder="e.g. Guitar" autoFocus returnKeyType="done" onSubmitEditing={handleCreate} />{error && <Text style={{ color: theme.colors.semantic.error }}>{error}</Text>}<Button label="Save" onPress={handleCreate} loading={saving} disabled={!title.trim()} fullWidth /></View></BottomSheet>
 <BottomSheet visible={Boolean(practiceSkill)} onClose={() => setPracticeSkill(null)}><View style={{ gap: theme.spacing[4] }}><Text style={{ color: theme.colors.text.primary, fontSize: theme.typography.card.fontSize, fontFamily: theme.typography.card.fontFamily }}>Practice {practiceSkill?.title}</Text><InputField label="Hours practiced today" value={hours} onChangeText={setHours} placeholder="e.g. 1.5" keyboardType="decimal-pad" autoFocus onSubmitEditing={savePractice} />{practiceError && <Text style={{ color: theme.colors.semantic.error }}>{practiceError}</Text>}<Button label="Save practice" onPress={savePractice} loading={saving} fullWidth /></View></BottomSheet>
 </SafeAreaView>;
}
