import React from 'react';
import { View, Text } from 'react-native';
import * as Icons from 'lucide-react-native';
import { useTheme } from '@/hooks/useTheme';
import type { TrackerGrid as TrackerGridData } from '@/services/trackerService';
const CELL_SIZE = 28; const LABEL_COLUMN_WIDTH = 140; const ROW_HEIGHT = 36;
interface TrackerGridProps { data: TrackerGridData; }
export function trackerContentSize(data: TrackerGridData) { return { width: LABEL_COLUMN_WIDTH + data.days.length * CELL_SIZE, height: 56 + data.rows.length * ROW_HEIGHT }; }
export function TrackerGrid({ data }: TrackerGridProps) { const theme = useTheme(); return <View><View style={{ flexDirection: 'row' }}><View style={{ width: LABEL_COLUMN_WIDTH, height: 20 }} /><View style={{ width: data.days.length * CELL_SIZE, height: 20, position: 'relative' }}>{data.days.map((day, i) => day.isFirstOfMonth ? <Text key={`m-${day.dateKey}`} numberOfLines={1} style={{ position: 'absolute', left: i * CELL_SIZE, color: theme.colors.text.secondary, fontSize: theme.typography.label.fontSize }}>{day.monthLabel}</Text> : null)}</View></View><View style={{ flexDirection: 'row' }}><View style={{ width: LABEL_COLUMN_WIDTH, height: 36, justifyContent: 'center' }}><Text style={{ color: theme.colors.text.secondary, fontSize: theme.typography.label.fontSize }}>ACTIVITY</Text></View>{data.days.map((day) => <View key={day.dateKey} style={{ width: CELL_SIZE, height: 36, alignItems: 'center', justifyContent: 'center', backgroundColor: day.isToday ? theme.colors.background.card : 'transparent', borderRadius: day.isToday ? theme.radius.sm : 0 }}><Text style={{ color: day.isToday ? theme.colors.accent.primary : theme.colors.text.secondary, fontSize: theme.typography.caption.fontSize }}>{day.dayLabel}</Text></View>)}</View>{data.rows.map((row) => { const IconComponent = (Icons as Record<string, any>)[row.icon] ?? Icons.Circle; return <View key={row.id} style={{ flexDirection: 'row', height: ROW_HEIGHT, alignItems: 'center' }}><View style={{ width: LABEL_COLUMN_WIDTH, flexDirection: 'row', alignItems: 'center', gap: theme.spacing[2], paddingRight: theme.spacing[2] }}><IconComponent size={14} color={theme.colors.text.secondary} /><Text numberOfLines={1} style={{ color: theme.colors.text.primary, fontSize: theme.typography.caption.fontSize, flex: 1 }}>{row.title}</Text></View>{row.cells.map((done, i) => <View key={data.days[i].dateKey} style={{ width: CELL_SIZE, height: ROW_HEIGHT - 4, borderWidth: 1, borderColor: theme.colors.border.default, alignItems: 'center', justifyContent: 'center' }}>{done && <Text style={{ color: theme.colors.accent.primary, fontSize: 16, fontWeight: '700' }}>✓</Text>}</View>)}</View>; })}</View>; }
